### ISSUE TITLE
retarget到 3D avatar 眼睛闭不上的问题

### ISSUE THREAD

**Issue by birdflies** [deepmo24/CPEM#1]
您好，大佬，我按照您的方法添加了 identity-consistent constraint to [deep3Drecons](https://github.com/sicxu/Deep3DFaceRecon_pytorch). 但是发现，还是没办法很好的将面部表情retarget到 3D avatar上，比如，在我的实验中，3D重构的mesh的眼睛是能够闭上的，但是retarget到 3D avatar上，眼睛几乎没有变化。想请教下您是否也曾经遇到过类似的问题？
如果遇到过，是怎么解决的呀？

**Comment by birdflies** [comment]
哈哈，话说，大佬最近有计划开源嘛

**Comment by deepmo24** [comment]
我们提出的方法能够对眼睛闭合进行较好的拟合和retarget。你说的情况可能与所使用的3DMM模型有关，我们使用了Facewarhouse的blendshape表情模型，更适合进行retarget。我们的方法在近期会进行开源，谢谢你的关注。

**Comment by birdflies** [comment]
谢谢大佬回复，期待您的开源。

**Comment by birdflies** [comment]
看到您文章的一些细节是在supplementary materials中，但是在AAAI上下载的文章，没有看到supplementary materials，您那边方不方便提供下补充材料的链接？谢谢啦～

**Comment by deepmo24** [comment]
你好，补充材料也会在最近几天上传到这个github上

**Comment by birdflies** [comment]
嗯嗯，谢谢哈。

**Comment by birdflies** [comment]
有一些技术疑问，咨询下大佬哈：就是在重构的时候，虽然是自监督训练，但眼睛闭合应该主要是通过关键点来监督的吧。那对关键点的GT要求是不是很高，如果训练的时候输入图片的关键点完全用3D face alignment和2D face alignment来生成，遇到一些关键点错误的负样本，需要挑出来重新处理吗？

**Comment by birdflies** [comment]
有一些技术疑问，咨询下大佬哈：就是在重构的时候，虽然是自监督训练，但眼睛闭合应该主要是通过关键点来监督的吧。那对关键点的GT要求是不是很高，如果训练的时候输入图片的关键点如果是完全用3D face alignment和2D face alignment来生成，遇到一些关键点错误的负样本，需要挑出来重新处理吗？

**Comment by deepmo24** [comment]
关键点监督确实是很重要的，我们通过结合3D face alignment和2D face alignment的关键点能够提高关键点标签的准确度（特别是眼睛闭合情况）。不过因为是学术论文，我们没有刻意检查或处理潜在的负样本，在业界可能会有这些处理吧。

**Comment by birdflies** [comment]
结合3D face alignment和2D face alignment的关键点，这里有点不太理解怎么去做的。大佬可以简单的介绍一下不。

- 按照我的理解，眼部闭合时候的关键点是最不准确的，观察3D face alignment的关键点，很多时候眼部闭合，但是关键点未完全闭合。我猜测您是不是处理的时候加了一些逻辑，比如说，3D face alignment和2D face alignment，计算上眼脸和下眼脸的距离，取距离最小的作为最终的关键点。

- 还有一个问题，就是您那边有没有特别添加一些闭眼的数据

**Comment by deepmo24** [comment]
我们的策略：
![image](https://user-images.githubusercontent.com/19352002/157390041-1efed021-0ad0-41bf-b41e-317ee4275ae8.png)

**Comment by birdflies** [comment]
> 我们的策略： ![image](https://user-images.githubusercontent.com/19352002/157390041-1efed021-0ad0-41bf-b41e-317ee4275ae8.png)
谢谢大佬及时回复哈
