### ISSUE TITLE
Question about the 2D landmarks detection on voxceleb2

### ISSUE THREAD

**Issue by Tianxinhuang** [deepmo24/CPEM#11]
Dear author,
Thanks for the brilliant work. But we met a question when detecting the 2D landmarks on the demo dataset of voxceleb2. It seems that we get different results using the preprocess/detect_landmarks.py by replacing the FaceAlignment parameter to LandmarksType.2D.

This is our generated results on id00025/eb8vIK6NrmE/00045_0218:
![image](https://user-images.githubusercontent.com/76049522/184868246-f0fff341-2013-4367-af3b-7a074b12f073.png)

This is the provided 2D landmarks in the demo dataset:
![image](https://user-images.githubusercontent.com/76049522/184868362-9bf3da00-bc82-49b5-99ac-1a0218c58064.png)

Could you please share us your code for the 2D landmark detection on voxceleb2? Thank you very much. Looking forward to your reply!

**Comment by deepmo24** [comment]
Hi, you'd better use 2D landmark detectors like [dlib](https://github.com/davisking/dlib) to detect 2D landmarks for more accurate detected results.
