### ISSUE TITLE
how long does it take to run landmarks detection algorithm on VoxCeleb2 dataset?

### ISSUE THREAD

**Issue by haonanhe** [deepmo24/CPEM#12]
Hi, thanks for your awsome codes! I'm new to facial reenactment and I'm trying to detect landmarks from VoxCeleb2 dataset. My algorithm runs pretty slow, which makes me crazy. I just wanna know how long does it take for you to detect landmarks from all those VoxCeleb2 frames? Thanks a lot!

**Comment by deepmo24** [comment]
Hi, I've forget the exact time I cost to detect landmarks. I suggest you can run multiple processes to detect landmarks for speeding up.
