### ISSUE TITLE
hi., how to mapping the FACS in 46 to Apple ARKit 56 blendshapes?

### ISSUE THREAD

**Issue by lucasjinreal** [deepmo24/CPEM#13]
hi., how to mapping the FACS in 46 to Apple ARKit 56 blendshapes?

**Comment by deepmo24** [comment]
Hi, the blendshapes we use (from Facewarehouse) partially overlaps with the blendshapes of Apple ARKit, but there are also some differences.  You can confirm the mappings according to the semantics of the expression blendshapes. The  semantics of our blendshapes can be found in [blendshape name](https://github.com/deepmo24/CPEM/blob/main/assets/blendshape_name.md).
