### ISSUE TITLE
如何驱动3D avatar

### ISSUE THREAD

**Issue by JACKYLUO1991** [deepmo24/CPEM#2]
作者你好，3DMM 47点是否与ARKIt52点存在对应关系或者说如何驱动类似论文中的3d人脸表情呢？

**Comment by deepmo24** [comment]
你好，我们使用的47个表情blendshape（来自Facewarehouse）与Apple ARKit使用的52个blendshape应该存在部分重合，但也有一些差异，具体对应关系你可以根据表情语义来确认。使用与我们具有相同语义的表情blendshape构建的3D角色人脸可以通过我们模型预测的表情系数进行直接驱动。

**Comment by JACKYLUO1991** [comment]
@deepmo24 感谢您的解答，再次打扰，这种3D模型去哪搜索到呢？

**Comment by deepmo24** [comment]
如果是工业应用的话，可以使用Blender等软件制作这样的3D人脸模型。

**Comment by JACKYLUO1991** [comment]
@谢谢您

**Comment by JACKYLUO1991** [comment]
您好，Facewarehouse的47点我看原论文说是按照FACS系统提取出来的，如下：
![image](https://user-images.githubusercontent.com/21237742/159235071-b7c2d2ed-46fe-460a-a664-18119ff4680b.png)
![image](https://user-images.githubusercontent.com/21237742/159235131-a0b67ab4-394a-4550-84a1-188574c05fbf.png)
我理解的对应关系是否正确呢？

**Comment by deepmo24** [comment]
这个对应关系不正确

**Comment by JACKYLUO1991** [comment]
是否方便提供paper中的3D avatar绑定脸呢?

**Comment by JACKYLUO1991** [comment]
我在作者上传的补充文献中找到了对应关系，有这个关系我就能对应绑定了，多谢作者...

**Comment by JACKYLUO1991** [comment]
我使用补充文献中的对应关系进行绑定，发现并不对应，作者是否能顺便给出46点的对应名称呢？

**Comment by deepmo24** [comment]
你好，我们上传了每个blendshape的对应名称: [blendshape name](https://github.com/deepmo24/CPEM/blob/main/assets/blendshape_name.md)

**Comment by JACKYLUO1991** [comment]
@deepmo24 非常感谢！
