### ISSUE TITLE
切换为flame？实时性？

### ISSUE THREAD

**Issue by bluels** [deepmo24/CPEM#4]
Hi，感谢分享这份工作！咨询下：

1.模型切换为flame的可行性？
2.模型推理的实时性？放一个video进去
3.与DECA的对比？

谢谢~！

**Comment by deepmo24** [comment]
你好，
1. 将3DMM模型换成Flame模型进行三维人脸重建应该是可行的，我们还没尝试过，你感兴趣的话可以基于我们框架进行尝试
2. 我们在论文中使用ResNet50作为网络骨架，模型推理速度和原始ResNet50基本一致。此外，我们在附录中使用了MobileNet-V2作为网络骨架进行实验，也取得较好的表情估计性能，其实时性更好。
3. 我们没有与DECA进行对比

**Comment by bluels** [comment]
多谢多谢！
