### ISSUE TITLE
Facial motion retargeting to 3D avatar

### ISSUE THREAD

**Issue by Neo1024** [deepmo24/CPEM#5]
Hi, thanks for your great work and the sharing of it :) I am impressed by the retargeting effect on 3D cartoon avatar shown in Figure 3 in the paper, especially compared with other approaches. Is it possible that you can share the assets of this 3D cartoon avatar model so that I can run the retargeting demo on the 3D avartar?

**Comment by deepmo24** [comment]
Hi, I am sorry this 3D avatar model can't be shared with you because its property rights belong to a company we cooperate with.

**Comment by Neo1024** [comment]
I see :) Thanks!

**Comment by Neo1024** [comment]
By the way, I tried to transfer the BFM blendshapes to a target avatar model. The individual blendshapes look good after the transformatio. However, when I started to use the reconstructed expression coefficients to drive the avatar model, I found some defect on the retarted avatar, which I guess is due to the inaccuracy during the deformation transform.  

I am wondering if I use a different source blendshape model, the deformation tranform may work better because BFM only has the facial region. Can you please share the original 46 FACS based blendshape model?

**Comment by deepmo24** [comment]
Hi, I think the transformed blendshape model may lose some details due to the optimization error in the deformation transfer process. So it would be better to use the original  blendshape model which is from the Facewarehouse database. Due to their distribution policy, you'd better apply for the database by yourself.

**Comment by Neo1024** [comment]
Thanks a lot!

**Comment by liushengtong-nreal** [comment]
> 多谢！
Sorry to bother you, can you share the 47 blendshapes corresponding to facewarehouse? I don't need its original scan data set, but I just want to experiment with the corresponding blendshape.
If possible or if you have a request, please email me 943436711@qq.com.
