### ISSUE TITLE
expression parameter

### ISSUE THREAD

**Issue by abcliguanxi** [deepmo24/CPEM#6]
hi,thks for your great work.i have one question.
1. Whether these expression parameters have actual physical meaning？just like arkit face blendshape.

looking forward to your reple.

**Comment by deepmo24** [comment]
Hi, the expression blendshapes have actual physical meaning, please see [blendshape name](https://github.com/deepmo24/CPEM/blob/main/assets/blendshape_name.md).

**Comment by abcliguanxi** [comment]
thks for your reply.I want to ask another question。
about “transfer the expression blendshapes from FaceWarehouse to BFM09” in the README。Are there any relevant code repositories or papers for reference?

**Comment by deepmo24** [comment]
please refer to this issue #3
