### ISSUE TITLE
How to process the videos in the VoxCeleb2 dataset?

### ISSUE THREAD

**Issue by gerwang** [deepmo24/CPEM#8]
Hi, thanks for the great work!

I wonder how to process the training data in the VoxCeleb2 dataset. The videos are 25fps, shall I use all the frames for training or sample a part of them? Do they need to be extracted as jpgs (if I extract each frame to jpg, I expect it to be very large)? Thank you!

**Comment by deepmo24** [comment]
We randomly sample 10 frames from each video clip at intervals of 10 frames when constructing the training set.

**Comment by gerwang** [comment]
Thanks! Solved my problem.
